### ISSUE TITLE
Could you send the dataset to me, please?

### ISSUE THREAD

**Issue by Michael-Yi-Rong** [antonismand/Personalized-News-Recommendation#1]
I have applied for it in the official website, but no response.

**Comment by antonismand** [comment]
Hi, have you received it? If I remember correctly it required a few days to get a download link.

**Comment by Michael-Yi-Rong** [comment]
> Hi, have you received it? If I remember correctly it required a few days to get a download link.

No, I used my edu email of my university, but no response.

**Comment by Michael-Yi-Rong** [comment]
![image](https://github.com/user-attachments/assets/88aadd5d-dbf3-48b3-ab08-79f38ff8b079)
contact also no use

**Comment by antonismand** [comment]
Unfortunately, I do not have the dataset downloaded, and even if I did, it would be against the terms of use to redistribute it.
